### ISSUE TITLE
Something about ElaIN

### ISSUE THREAD

**Issue by AnnapolisWong** [ChaoyueSong/3d-corenet#1]
Thank you very much for your paper!
I found the expression in code normalization.py, line 39, is different from the formula(7) of your paper, the code plus x, I think this is unnecessary. Would you mind interpreting about this?
Thanks!

**Comment by ChaoyueSong** [comment]
Hi,
Thanks for your interest.
If you check [SPADE](https://github.com/NVlabs/SPADE/blob/fecacc920c1367a038995c45a39c15f6521ca64f/models/networks/normalization.py#L108) and [CoCosNet](https://github.com/microsoft/CoCosNet/blob/f8007d9369cc11bc04709ef02dedbbf718d74414/models/networks/normalization.py#L239), they both plus x for their normalization layer. We think plus x will make the training more stable. If remove it, the training may fail with loss equals Nan.

**Comment by AnnapolisWong** [comment]
Thank you for the thorough answer! I got it :)
