### ISSUE TITLE
About other categories of SMAL data generation?

### ISSUE THREAD

**Issue by hanbinbin-web** [ChaoyueSong/3d-corenet#3]
Hello, thank you very much for your work, I have a question about the production of data sets. The original SMAL file only provides the data download of hippocampus. How did you get the data of other categories? Looking forward to your reply?

**Comment by ChaoyueSong** [comment]
Hi, thanks for your interest. Please refer to the following code, you can get other categories from 'toy_betas'.
```
from smpl_webuser.serialization import load_model
import pickle as pkl
# Load the smal model 
model_path = 'smal_CVPR2017.pkl'
model = load_model(model_path)
# Load the family clusters data
model_data_path = 'smal_CVPR2017_data.pkl'
data = pkl.load(open(model_data_path))
# Get all categories from toys_betas
for i, betas in enumerate(data['toys_betas']):
    model.betas[:] = betas
```

**Comment by hanbinbin-web** [comment]
Thanks for your reply, I have solved the problem.
